export const rollupAbi = [
    {
        type: 'function',
        name: 'getVersion',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getSlasher',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        name: 'getPendingSlasher',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            { name: 'slasher', type: 'address' },
            { name: 'readyAt', type: 'uint256' },
        ],
    },
    {
        type: 'function',
        name: 'getLegacySlasher',
        stateMutability: 'view',
        inputs: [],
        outputs: [
            { name: 'slasher', type: 'address' },
            { name: 'authorizedUntil', type: 'uint256' },
        ],
    },
    {
        type: 'function',
        name: 'getCurrentSlot',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getCurrentEpoch',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getStatus',
        stateMutability: 'view',
        inputs: [{ name: '_attester', type: 'address' }],
        outputs: [{ name: '', type: 'uint8' }],
    },
    {
        type: 'function',
        name: 'getGenesisTime',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getEscapeHatchForEpoch',
        stateMutability: 'view',
        inputs: [{ name: '_epoch', type: 'uint256' }],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        name: 'getSlotAt',
        stateMutability: 'view',
        inputs: [{ name: '_timestamp', type: 'uint256' }],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getEpochDuration',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        name: 'getSlotDuration',
        stateMutability: 'view',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'event',
        name: 'Slashed',
        inputs: [
            { name: 'attester', type: 'address', indexed: true },
            { name: 'amount', type: 'uint256', indexed: false },
        ],
    },
] as const;
